# Generated by Django 2.1.4 on 2019-04-12 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.RemoveField(
            model_name='song',
            name='songs',
        ),
    ]
